### ISSUE TITLE
Deprecated selector in `hasklig/styles/hasklig.less`

### ISSUE THREAD

**Issue by pmlodawski** [adilparvez/atom-hasklig#1]
In `hasklig/styles/hasklig.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `[hasklig-font='hasklig-extra-light'] atom-text-editor::shadow .comment` => `[hasklig-font='hasklig-extra-light'] atom-text-editor.editor .syntax--comment`

* `[hasklig-font='hasklig-extra-light'] atom-text-editor::shadow .string` => `[hasklig-font='hasklig-extra-light'] atom-text-editor.editor .syntax--string`

* `[hasklig-font='hasklig-light'] atom-text-editor::shadow .comment` => `[hasklig-font='hasklig-light'] atom-text-editor.editor .syntax--comment`

* `[hasklig-font='hasklig-light'] atom-text-editor::shadow .string` => `[hasklig-font='hasklig-light'] atom-text-editor.editor .syntax--string`

* `[hasklig-font='hasklig-regular'] atom-text-editor::shadow .comment` => `[hasklig-font='hasklig-regular'] atom-text-editor.editor .syntax--comment`

* `[hasklig-font='hasklig-regular'] atom-text-editor::shadow .string` => `[hasklig-font='hasklig-regular'] atom-text-editor.editor .syntax--string`

* `[hasklig-font='hasklig-medium'] atom-text-editor::shadow .comment` => `[hasklig-font='hasklig-medium'] atom-text-editor.editor .syntax--comment`

* `[hasklig-font='hasklig-medium'] atom-text-editor::shadow .string` => `[hasklig-font='hasklig-medium'] atom-text-editor.editor .syntax--string`

* `[hasklig-font='hasklig-semibold'] atom-text-editor::shadow .comment` => `[hasklig-font='hasklig-semibold'] atom-text-editor.editor .syntax--comment`

* `[hasklig-font='hasklig-semibold'] atom-text-editor::shadow .string` => `[hasklig-font='hasklig-semibold'] atom-text-editor.editor .syntax--string`

* `[hasklig-font='hasklig-bold'] atom-text-editor::shadow .comment` => `[hasklig-font='hasklig-bold'] atom-text-editor.editor .syntax--comment`

* `[hasklig-font='hasklig-bold'] atom-text-editor::shadow .string` => `[hasklig-font='hasklig-bold'] atom-text-editor.editor .syntax--string`

* `[hasklig-font='hasklig-black'] atom-text-editor::shadow .comment` => `[hasklig-font='hasklig-black'] atom-text-editor.editor .syntax--comment`

* `[hasklig-font='hasklig-black'] atom-text-editor::shadow .string` => `[hasklig-font='hasklig-black'] atom-text-editor.editor .syntax--string`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by adilparvez** [comment]
Thanks, fixed now.

**Comment by pmlodawski** [comment]
Thanks :)
