### ISSUE TITLE
Support for Hasklig 1.1

### ISSUE THREAD

**Issue by wende** [adilparvez/atom-hasklig#2]
As far as I see there is no new ligatures

**Comment by adilparvez** [comment]
The version of Hasklig bundled is 1.1. If you look at the release notes [here](https://github.com/i-tu/Hasklig/#release-notes), you can see the new ligatures added.

![image](https://cloud.githubusercontent.com/assets/6894766/26577200/7fb43464-4523-11e7-96aa-e5ed9fd17788.png)

It may be that atom's tokeniser for the language you are using, breaks these sequences up. The above image was taken with the language set to Haskell.

**Comment by wende** [comment]
Oh. You're right. It must be that.
Elm here:
<img width="323" alt="screen shot 2017-05-30 at 16 01 58" src="https://cloud.githubusercontent.com/assets/4634386/26587002/5b8210e2-4551-11e7-90c6-15d90062747d.png">
And Elixir here
<img width="317" alt="screen shot 2017-05-30 at 16 02 21" src="https://cloud.githubusercontent.com/assets/4634386/26587016/6754d5ee-4551-11e7-84af-255857ea4a2e.png">

**Comment by wende** [comment]
It's a shame it's not universal. Nevermind then.
By the way I love this package. Hands down 🙏

**Comment by adilparvez** [comment]
Thanks. You could open an issue on the package for the language you're using, stating that the grammar splits certain character sequences up in a way that stops ligatures from working correctly.
